services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    # renewal loop (safe to keep running)
    command: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - ./ExpanseTraker:/app
    command: >-
      sh -c "python manage.py wait_for_db
      && python manage.py migrate
      && gunicorn ExpanseTraker.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - postgres
      - redis
      - celery
      - celery-beat

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=expanse_tracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"

  redis:
    image: redis:latest
    expose:
      - "6379"

  celery:
    build: .
    env_file:
      - .env
    command: celery -A ExpanseTraker worker --loglevel=info
    volumes:
      - ./ExpanseTraker:/app
    depends_on:
      - postgres
      - redis

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A ExpanseTraker beat --loglevel=info
    volumes:
      - ./ExpanseTraker:/app
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: {}
  letsencrypt: {}
  certbot-webroot: {}

