# Generated by Django 5.2 on 2026-05-04 18:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expanse", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="recurring",
            managers=[
                ("recurringObjects", django.db.models.manager.Manager()),
            ],
        ),
    ]
