# Generated by Django 5.2 on 2026-05-18 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expanse", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="start_date",
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="weekly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
