# Generated by Django 5.2 on 2026-05-18 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expanse", "0003_remove_budget_end_date_remove_budget_start_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category", "budget_type")},
        ),
    ]
