# Generated by Django 5.2 on 2026-05-06 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expanse", "0003_alter_recurring_managers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "is_default")},
        ),
    ]
