# Generated by Django 5.2 on 2026-05-06 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expanse", "0004_alter_category_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "user")},
        ),
    ]
