# Generated by Django 5.2 on 2026-10-01 07:38

from django.db import migrations, models


def clear_s3_profile_pictures(apps, schema_editor):
    # S3 URLs no longer resolve; fall back to the local default picture
    User = apps.get_model("user", "User")
    User.objects.filter(profile_picture__startswith="http").update(profile_picture=None)


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(clear_s3_profile_pictures, migrations.RunPython.noop),
    ]
