# Generated by Django 5.2 on 2026-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(
                blank=True,
                default="http://localhost:8000//media/default/default_profile_picture.png",
                null=True,
            ),
        ),
    ]
