# Generated by Django 5.2 on 2026-05-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(
                blank=True,
                default="https://expanse-treaker-ai.s3.ap-south-1.amazonaws.com/profile-pictures/default/default-profile-picture.png",
                null=True,
            ),
        ),
    ]
